fix: Add `aggregation` in OneYearOldTimeseries query indexes
cozy/coachCO2 pull request #138
Opened 2022-06-06 14:38 UTC by JF-Cozy

2022-06-06 15:07 UTC, Merkur39 approved these changes

2022-06-06 16:14 UTC, paultranvan approved these changes

2022-06-06 16:26 UTC, paultranvan requested changes
The query should use a `.select(['aggregation'])` to benefit from https://github.com/cozy/coachCO2/pull/133

2022-06-07 07:48 UTC, JF-Cozy commented
> The query should use a `.select(['aggregation'])` to benefit from #133

@paul pour https://github.com/cozy/coachCO2/pull/138 avec le select on a "le bug de banks", c'est à dire que si on rajoute le select, cela impacte le résultat de la requête qu'on construit avec `buildTimeseriesQueryByAccountId` et ça "lie" les deux requêtes.

Pour info j'ai testé avec `.select(['startDate', 'aggregation'])` (startDate est aussi un attribut nécessaire). J'ai bien la bonne réponse dans le réseau pour `buildOneYearOldTimeseriesWithAggregationByAccountId` et `buildTimeseriesQueryByAccountId`, par contre quand je log l'object retourné (donc réponse de cozy-client) https://github.com/cozy/coachCO2/blob/master/src/components/Views/Trips.jsx#L32 je n'ai pas le bon comportement, j'ai d'abord les bonnes données, puis un tableau vide (une fois que `buildTimeseriesQueryByAccountId` s'exécute).

Avec `.select(['cozyMetadata.sourceAccount', 'startDate', 'aggregation'])` tout est ok pour `buildTimeseriesQueryByAccountId` (côté réseau et côté cozy-client) mais c'est la réponse de cozy-client pour `buildOneYearOldTimeseriesWithAggregationByAccountId` qui déconne https://github.com/cozy/coachCO2/blob/master/src/components/CO2EmissionsChart/CO2EmissionsChart.jsx#L25 car j'ai l'object en entier, alors que je ne devrais avoir que les 3 attributs (ce qui est le cas dans le réseau par contre).

@Merkur39 tu confirmes que c'est le même sujet que https://github.com/cozy/cozy-client/issues/1175 ?

En l'état donc, je suggère d'éviter l'ajout du `.select`

2022-06-07 07:57 UTC, merged